### ISSUE TITLE
Logging internal work

### ISSUE THREAD

**Issue by J0o0** [peakshift/PSIPs#4]
```yaml
Title: Internal work -logging guideline
Author: @j0o0
Status: Draft
Type: Process
```

# Abstract

# Motivation

# Specification
Please suggest #meta-tags for the issues you most frequently log for internal work. 

The current main categories of work and suggested meta-tags are:

1. Communication : #team-call  #client-call #team-discussion
2. Administrative: #accounting #documentation #README #document-management
3. Technical: #code-push #code-test #code-inspect #code-creation #code-fix
4. Research: #research-[topic of your research]
5. Design: 
6. Planning: #personal-plan #client-tasklist
7. Other:
